### PR TITLE
Move info about testing from README to testing.md

### PR DESCRIPTION
**Pull request by mpoke**
# Description

Move info about testing from README to testing.md

## Type of change

- [x] `Docs`: Adds documentation

### CODE REVIEW

**Comment by smarshall-spitzbart** [comment]
What is the advantage of a wiki over git tracking these test instructions? Imo it's nice to see req changes to testing instructions

**Comment by mpoke** [comment]
> What is the advantage of a wiki over git tracking these test instructions? Imo it's nice to see req changes to testing instructions

Fair point. I just wanted to clean up our README. Maybe we should have a `testing.md` file into docs that contains all this info. What do you think?

**Comment by smarshall-spitzbart** [comment]
> > What is the advantage of a wiki over git tracking these test instructions? Imo it's nice to see req changes to testing instructions
> 
> Fair point. I just wanted to clean up our README. Maybe we should have a `testing.md` file into docs that contains all this info. What do you think?

Yea this seems solid to me 👍, the main readme could then just link to the `testing.md`

**Review by smarshall-spitzbart — APPROVED** [review]
LGTM

**Review by MSalopek — APPROVED** [review]
Nice!

**Pull request merged**
