### PR TITLE
first: gofumpt

### PR DESCRIPTION
**Pull request by faddat**
# Description

this PR was generated by running:

```
bash gofumpt -w -l .
```

This will cover the majority of changes to the repository. 

Merge before #820.  Please.

## Type of change

If you've checked more than one of the first three boxes, consider splitting this PR into multiple PRs!

- [ ] `Feature`: Changes and/or adds code behavior, irrelevant to bug fixes
- [ ] `Fix`: Changes and/or adds code behavior, specifically to fix a bug
- [x] `Refactor`: Changes existing code style, naming, structure, etc.
- [ ] `Testing`: Adds testing
- [ ] `Docs`: Adds documentation

## Regression tests

If `Refactor`, describe the new or existing tests that verify no behavior was changed or added where refactors were introduced.

## New behavior tests

If `Feature` or `Fix`, describe the new or existing tests that verify the new behavior is correct and expected.

## Versioning Implications

- [ ] This PR will affect [semantic versioning as defined for ICS](../CONTRIBUTING.md#semantic-versioning)

If the above box is checked, which version should be bumped?

- [ ] `MAJOR`: Consensus breaking changes to both the provider and consumers(s), including updates/breaking changes to IBC communication between provider and consumer(s)
- [ ] `MINOR`: Consensus breaking changes which affect either only the provider or only the consumer(s)
- [x] `PATCH`: Non consensus breaking changes

## Targeting

Please select one of the following:

- [x] This PR is only relevant to main
- [ ] This PR is relevant to main, and should also be back-ported to ____ (ex: v1.0.0 and v1.1.0)
- [ ] This PR is only relevant to ____ (ex: v1.0.0, v1.1.0, and v1.2.0)

### CODE REVIEW

**Comment by faddat** [comment]
Determinstically formats code.  Makes merging sp-sp or one of the orther 47 upgrades easier since those have also been formnatted.

**Comment by jtremback** [comment]
@faddat This looks good but due to a test renaming on main it doesn't merge cleanly anymore. It may be easiest to just re-run gofumpt on current main and we can get that merged tomorrow.

**Comment by faddat** [comment]
It does merge cleanly. I already did the merge yesterday before the call

**Review by smarshall-spitzbart — APPROVED** [review]
This is indeed all formatting related changes

**Comment by faddat** [comment]
....which can be deterministically generated with the command provided at the top, right?

**Comment by faddat** [comment]
maybe you should consider applying it to your pull requests using the command at the top, please?

**Comment by faddat** [comment]
oh right; lol -- really should only have 45.15 and 4.3.0

**Review by jtremback — APPROVED** [review]
LGTM

**Pull request merged**
