### PR TITLE
refactor: TrustingPeriodFraction should be a fraction.

### PR DESCRIPTION
**Pull request by glnro**
# Description
Refactoring `TrustingPeriodFraction` per #408. Previously this value was stored as a divisor (`int`) for `UnbondingPeriod`. The new value is a multiplied factor stored as a `string` decimal fraction.

## Linked issues

Closes: #408 

## Type of change

- [x] `Refactor`: Changes existing code style, naming, structure, etc.

## Regression tests

`TestMakeConsumerGenesis` needed to be updated with a `new trusting_period` value to compare against in the genesis as the new default value was updated to reflect 2/3 threshold (`"0.66"`)

### CODE REVIEW

**Comment by danwt** [comment]
`66%` is less than 2/3 of 100. Is that intentional?

**Comment by glnro** [comment]
> `66%` is less than 2/3 of 100. Is that intentional?

For the sake of a first pass yes, but I'd like to have a discussion about how we'd want to handle this, if `"0.67"` is sufficient or if we should instead represent in a different format.

**Review by mpoke — APPROVED** [review]
LGTM. Nice work @glnro.

**Comment by mpoke** [comment]
> > `66%` is less than 2/3 of 100. Is that intentional?
> 
> For the sake of a first pass yes, but I'd like to have a discussion about how we'd want to handle this, if `"0.67"` is sufficient or if we should instead represent in a different format.

I think it's irrelevant given that's just a default value and the default unbonding period is 3 weeks (504 h), which means the default trusting period  would be either ~332 h or ~337 h.

**Review by MSalopek — APPROVED** [review]
LGTM

**Comment by jtremback** [comment]
`"0.6666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666"`

**Pull request merged**
