### PR TITLE
fix: fixed QueryAllPairsValConAddrByConsumerChainID output formatting

### PR DESCRIPTION
**Pull request by freak12techno**
## Description

Fixes the issue described here: https://github.com/cosmos/interchain-security/issues/1251#issuecomment-2016665369

Converts QueryAllPairsValConAddrByConsumerChainID output to consumer addresses, so instead of raw bytes in gRPC/REST response we now have this:
image

I patched my Gaia node with this: https://api.cosmos.quokkastake.io/interchain_security/ccv/provider/consumer_chain_id?chain_id=neutron-1, seems to work more correct, also tested it with gRPC and it also works.

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [x] Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [x] Added `!` to the type prefix if the change is [state-machine breaking](https://github.com/cosmos/interchain-security/blob/main/RELEASES.md#breaking-changes)
* [x] Confirmed this PR does not introduce changes requiring state migrations, OR migration code has been added to consumer and/or provider modules
* [x] Targeted the correct branch (see [PR Targeting](https://github.com/cosmos/interchain-security/blob/main/CONTRIBUTING.md#pr-targeting))
* [x] Provided a link to the relevant issue or specification
* [x] Followed the guidelines for [building SDK modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/build/building-modules/00-intro.md)
* [x] Included the necessary unit and integration [tests](https://github.com/cosmos/interchain-security/blob/main/CONTRIBUTING.md#testing)
* [ ] Added a changelog entry to `CHANGELOG.md`
* [x] Included comments for [documenting Go code](https://blog.golang.org/godoc)
* [x] Updated the relevant documentation or specification
* [x] Reviewed "Files changed" and left comments if necessary 
* [x] Confirmed all CI checks have passed
* [x] If this PR is library API breaking, bump the go.mod version string of the repo, and follow through on a new major release

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed `!` the type prefix if the change is state-machine breaking
* [ ] confirmed this PR does not introduce changes requiring state migrations, OR confirmed migration code has been added to consumer and/or provider modules
* [ ] confirmed all author checklist items have been addressed
* [ ] reviewed state machine logic
* [ ] reviewed API design and naming
* [ ] reviewed documentation is accurate
* [ ] reviewed tests and test coverage

### CODE REVIEW

**Comment by freak12techno** [comment]
@mpoke need someone to review this, can you review that or tag somebody please?

**Comment by freak12techno** [comment]
Also, one off-top thing that's not related but that I can fix in this PR, if that's an issue (not sure if it is):
https://github.com/cosmos/interchain-security/blob/main/proto/interchain_security/ccv/provider/v1/query.proto#L203 here it has 2 keys with `yaml:"address"`, wonder if it may cause any issues or if it's expected?

**Review by insumity — APPROVED** [review]
> Also, one off-top thing that's not related but that I can fix in this PR, if that's an issue (not sure if it is):
https://github.com/cosmos/interchain-security/blob/main/proto/interchain_security/ccv/provider/v1/query.proto#L203 here it has 2 keys with yaml:"address", wonder if it may cause any issues or if it's expected?

Yes, it would be nice to have `consumer_address` and `provider_address` instead of both being `address`.

LGTM

**Comment by freak12techno** [comment]
@insumity okay, done and also fixed tests, should do the trick as it's now passing on my laptop locally.
Can you clarify whether this proto file change would be breaking and therefore if I need to add ! to my PR?

**Comment by insumity** [comment]
@freak12techno This is a _node API breaking_ change, not a [_state-machine breaking_](https://github.com/cosmos/interchain-security/blob/main/RELEASES.md#breaking-changes) one.

**Comment by freak12techno** [comment]
@insumity gotcha, I thought whether changing the yaml thing in proto file would result in a breaking change or not, but regardless of the yaml thing it will be API breaking, as it returns data in a different format now, am I correct?
Also, let me know if I should use another prefix or signal in any way that this change would change the API response (not its format, but the data it returns).

**Comment by freak12techno** [comment]
@insumity gotcha. Last question: I see mbt tests failing here, but they seem to also fail in other PRs, can you clarify whether this is ok or should I update something in my PR to make it pass?

**Comment by freak12techno** [comment]
@insumity @p-offtermatt can we get this merged?

**Review by p-offtermatt — APPROVED** [review]
LGTM, thanks! Will merge

**Comment by freak12techno** [comment]
@p-offtermatt sorry for pinging again, I think auto merge won't work here as there's a failed CI check which is failing not because of my changes. Can you maybe merge it manually?

**Pull request merged**
