### PR TITLE
docs: draft adr-004 for separating consumer and provider versioning

### PR DESCRIPTION
**Pull request by MSalopek**
## Description

This draft PR introduces ADR-004 which outlines changes for separating provider and consumer libraries.

Closes: https://github.com/cosmos/interchain-security/issues/889

Related issues:
* https://github.com/cosmos/interchain-security/issues/801

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] included the correct `docs:` prefix in the PR title
- [x] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/interchain-security/blob/main/CONTRIBUTING.md#pr-targeting))
- [x] provided a link to the relevant issue or specification
- [x] reviewed "Files changed" and left comments if necessary 
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] Confirmed the correct `docs:` prefix in the PR title
- [ ] Confirmed all author checklist items have been addressed 
- [ ] Confirmed that this PR only changes documentation
- [ ] Reviewed content for consistency
- [ ] Reviewed content for spelling and grammar
- [ ] Tested instructions (if applicable)
- [ ] Checked that the documentation website can be built and deployed successfully (run `make build-docs`)

### CODE REVIEW

**Comment by faddat** [comment]
Overall, I'm not in favor of this design, since it breaks the patterns commonly used in Cosmos.  If we consider the cosmos-sdk, it does not yet use module paths, but the whole repository is a single SDK version.

ibc-go works this way too. 

When we spoke about this the other day, you mentioned in-memory testing, and I'm curious how breaking into one or more go modules can help with that -- could you explain furter?

**Comment by smarshall-spitzbart** [comment]
> breaks the patterns commonly used in Cosmos

Cosmos-sdk has `go.mod` files within subdirectories of `x/`, see [here](https://github.com/cosmos/cosmos-sdk/blob/27c6be521a733cf657cd8d23e10e25b5bdae2d14/x/circuit/go.mod), [here](https://github.com/cosmos/cosmos-sdk/blob/27c6be521a733cf657cd8d23e10e25b5bdae2d14/x/evidence/go.mod), [here](https://github.com/cosmos/cosmos-sdk/blob/27c6be521a733cf657cd8d23e10e25b5bdae2d14/x/nft/go.mod) as examples. 

> you mentioned in-memory testing, and I'm curious how breaking into one or more go modules can help with that

The main value prop of introducing separate `go.mod`s for consumer and provider is to enable separate release cycles with more meaningful semver

**Comment by faddat** [comment]
Okay, I'm going to address your point separately but I need to make really clear that in fact we achieve the same thing by changing the module paths.  

IBC has been using module path versioning for a long time now, and it works great.

Earlier I thought that it had been mentioned that this was being done because of in memory testing?

**Comment by smarshall-spitzbart** [comment]
Closing in favor of https://github.com/cosmos/interchain-security/issues/1216

**Pull request closed without merging**
