### PR TITLE
update buf googleapis dependency

### PR DESCRIPTION
**Pull request by MSalopek**
An issue manifested because buf dependencies were out of date.

Running `make proto-gen` would fail with err citing that googleapis depedency cannot be found.

Updated buf dependencies using
buf mod update --only buf.build/googleapis/googleapis

Changed tidy to be compatible to 1.18 only

Closes: #347

### CODE REVIEW

**Review by danwt — DISMISSED** [review]
Awesome, thanks for this!

**Comment by marbar3778** [comment]
update here as well
https://github.com/cosmos/interchain-security/blob/main/Makefile#L44

**Comment by marbar3778** [comment]
https://github.com/cosmos/cosmos-sdk/pull/13168

**Comment by MSalopek** [comment]
> update here as well https://github.com/cosmos/interchain-security/blob/main/Makefile#L44

Unfortunately when I bump the version and change image name to this
```
protoVer=0.8
protoImageName=ghcr.io/cosmos/proto-builder:$(protoVer)
```

Running `make proto-gen` fails with:
```
$: make proto-gen
Generating Protobuf files
Unable to find image 'sh:latest' locally
docker: Error response from daemon: pull access denied for sh, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
make: *** [Makefile:54: proto-gen] Error 125
```

**Comment by marbar3778** [comment]
> Unable to find image 'sh:latest' locally

not sure where this image is coming form?

**Comment by MSalopek** [comment]
> > Unable to find image 'sh:latest' locally
> 
> not sure where this image is coming form?

It was user error, I managed to resolve it.

When using v0.8 the following error happens:
```
make proto-gen        
Generating Protobuf files
Unable to find image 'ghcr.io/cosmos/proto-builder:0.8' locally
0.8: Pulling from cosmos/proto-builder
9b18e9b68314: Pull complete 

...

Digest: sha256:0d6114557b9a2c0659fc611e8acb970e4c036a1fa7d806dedc2f6302f1302018
Status: Downloaded newer image for ghcr.io/cosmos/proto-builder:0.8
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
exec /bin/sh: exec format error
make: *** [Makefile:54: proto-gen] Error 1
```

Changing version to **v0.9.0** fixes it.

There are changes in `third_party/proto/cosmos/staking/v1beta1/staking.proto` so buyers beware.

**Comment by jtremback** [comment]
@MSalopek Is this ready to merge? Seems from the discussion that maybe it should still be marked as draft. Let me know if it's ready or not.

**Comment by MSalopek** [comment]
> @MSalopek Is this ready to merge? Seems from the discussion that maybe it should still be marked as draft. Let me know if it's ready or not.

Ready for review.

**Review by sainoe — APPROVED** [review]

**Pull request merged**
