### PR TITLE
update proto build system

### PR DESCRIPTION
**Pull request by faddat**
# Description

Update the build system for .proto files:

* use an image compatible with go 1.20
* ~rename the import path for proofs.proto to be compatible with that image~
* rebuild protobufs dependencies

I'd also like to add that I think that this PR is of hidden importance.  I think that we very much need to make sure that it works.  Right now we build ics with protos that don't match the versions of the software that we are using -- **in the present day**.

When we update to those newer .proto files, we find that the build fails.  I'll open a bug issue. 

## Type of change

If you've checked more than one of the first three boxes, consider splitting this PR into multiple PRs!

- [ ] `Feature`: Changes and/or adds code behavior, irrelevant to bug fixes
- [ ] `Fix`: Changes and/or adds code behavior, specifically to fix a bug
- [ ] `Refactor`: Changes existing code style, naming, structure, etc.
- [ ] `Testing`: Adds testing
- [ ] `Docs`: Adds documentation

## Regression tests

If `Refactor`, describe the new or existing tests that verify no behavior was changed or added where refactors were introduced.

## New behavior tests

If `Feature` or `Fix`, describe the new or existing tests that verify the new behavior is correct and expected.

## Versioning Implications

- [ ] This PR will affect [semantic versioning as defined for ICS](../CONTRIBUTING.md#semantic-versioning)

If the above box is checked, which version should be bumped?

- [ ] `MAJOR`: Consensus breaking changes to both the provider and consumers(s), including updates/breaking changes to IBC communication between provider and consumer(s)
- [ ] `MINOR`: Consensus breaking changes which affect either only the provider or only the consumer(s)
- [x] `PATCH`: Non consensus breaking changes

## Targeting

Please select one of the following:

- [x] This PR is only relevant to main
- [x] This PR is relevant to main, and should also be back-ported to v1.2.x (ex: v1.0.0 and v1.1.0)
- [ ] This PR is only relevant to ____ (ex: v1.0.0, v1.1.0, and v1.2.0)

### CODE REVIEW

**Comment by jtremback** [comment]
Thanks! Are the tests supposed to be failing now? Seeing a message

```
--- FAIL: TestCoreSuite/TestAssumptionsSetup (0.00s)
        suite.go:87: test panicked: concrete type *types.ConsumerAdditionProposal has already been registered under typeURL /, cannot register *types.ConsumerRemovalProposal under same typeURL. This usually means that there are conflicting modules registering different concrete types for a same interface implementation
```

**Comment by faddat** [comment]
hey I need to mark this as draft, and I don't know why it fails.

**Comment by faddat** [comment]
much better

https://github.com/cosmos/gaia/pull/2432

**Comment by faddat** [comment]
seems dangerous, sadly

**Pull request closed without merging**
