### PR TITLE
[draft] Validator key delegation

### PR DESCRIPTION
**Pull request by jtremback**
This should do it. Needs some cli methods and need to figure how to serialize keys correctly.

Closes https://github.com/cosmos/interchain-security/issues/26

### CODE REVIEW

**Comment by jtremback** [comment]
Passing this off to @danwt. 

The way I am doing it here is not going to work. Since what is sent over is a list of changes, not a list of all current powers, just substituting out the key like I do here is going to result in nonsensical updates.

There might be a few alternate approaches:

1. Synthesize validator changes: When a key is delegated, generate a valset update that makes it look to the consumer chain like the old key left the set and the new key was brought in with the same power. The consumer chain will not know that they are the same validator. After that, the keys can simply be substituted in updates like they are here. To make slashing work, you would probably need to switch the delegated key for the real key in slashing packets.

2. Delegate on the consumer: When someone delegates a key, send a packet with the key delegation to the consumer chain. Then the consumer chain will do the substitution. More code, and I'm not exactly clear on what the benefit would be over the option above.

**Comment by mpoke** [comment]
A third option would be to expand the `abci.ValidatorUpdate` data structure. Currently it contains a `PubKey` and the `Power` as `int64`. We could also add the consensus address `Address` of the validator  on the provider chain. In case the validator doesn't use another key for a consumer chain, then `Address  = hash(PubKey)`. Otherwise, the `PubKey` is the key used on the consumer chain. 

Consequently, `VSCPacket`s contain power updates and validator key updates. `SlashPacket`s require the consensus address on the provider (i.e., `Address`), which the CCV module can retrieve from the mapping kept internally.

Note that the mapping of old validator keys must be kept to avoid a validator misbehaving on the consumer and then changing its address to not get slashed.

**Comment by danwt** [comment]
@mpoke I don't have a strong opinion on your question.

**Comment by jtremback** [comment]
Closing this for now, until it is more finished

**Pull request closed without merging**
