### PR TITLE
Remove  StakingHooksTemplate from provider hooks

### LINKED ISSUE #329: use expected_keepers for staking hooks
Is there a reason why staking hooks template is used over StakingHooks interface like 

https://github.com/cosmos/cosmos-sdk/blob/2a813177b207d85078263fe5900d6912b5c8dd24/x/slashing/types/expected_keepers.go#L61?

### PR DESCRIPTION
**Pull request by sainoe**
Change the provider hooks to not use a `StakingHooksTemplate` struct since it was deleted in the [IS-SDK merge](https://github.com/cosmos/cosmos-sdk/pull/13122).

* close #329

### CODE REVIEW

**Review by mpoke — APPROVED** [review]
LGTM

**Review by jtremback — APPROVED** [review]
LGTM

**Comment by jtremback** [comment]
> I think we should hold approval of this until we know if we should already be pointing at the upstream changes
> 
> * https://github.com/cosmos/interchain-security/blob/e5f4ea5c00d571a024c2a0bd6903ac77d42dfb38/go.mod#L6
> * [feat!: IS rebase cosmos-sdk#13122](https://github.com/cosmos/cosmos-sdk/pull/13122)

This works regardless, right?

**Comment by mpoke** [comment]
@danwt Are we ready to merge this?

**Comment by danwt** [comment]
Ah yeah should be fine

**Pull request merged**
