### PR TITLE
feat: add query for getting all assigned keys

### PR DESCRIPTION
**Pull request by freak12techno**
## Description

Closes: #984

Adds provider query to fetch all assigned keys (either all of them, or filtered by consumer chain ID).
This is quite an alpha version that was never tested yet, please treat it accordingly.

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [x] Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [x] Added `!` to the type prefix if the change is [state-machine breaking](https://github.com/cosmos/interchain-security/blob/main/RELEASES.md#breaking-changes)
* [x] Confirmed this PR does not introduce changes requiring state migrations, OR migration code has been added to consumer and/or provider modules
* [x] Targeted the correct branch (see [PR Targeting](https://github.com/cosmos/interchain-security/blob/main/CONTRIBUTING.md#pr-targeting))
* [x] Provided a link to the relevant issue or specification
* [x] Followed the guidelines for [building SDK modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/build/building-modules/00-intro.md)
* [ ] Included the necessary unit and integration [tests](https://github.com/cosmos/interchain-security/blob/main/CONTRIBUTING.md#testing)
* [ ] Added a changelog entry to `CHANGELOG.md`
* [ ] Included comments for [documenting Go code](https://blog.golang.org/godoc)
* [ ] Updated the relevant documentation or specification
* [ ] Reviewed "Files changed" and left comments if necessary 
* [ ] Confirmed all CI checks have passed
* [x] If this PR is library API breaking, bump the go.mod version string of the repo, and follow through on a new major release

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed `!` the type prefix if the change is state-machine breaking
* [ ] confirmed this PR does not introduce changes requiring state migrations, OR confirmed migration code has been added to consumer and/or provider modules
* [ ] confirmed all author checklist items have been addressed
* [ ] reviewed state machine logic
* [ ] reviewed API design and naming
* [ ] reviewed documentation is accurate
* [ ] reviewed tests and test coverage

### CODE REVIEW

**Comment by mpoke** [comment]
@freak12techno please note this similar PR https://github.com/cosmos/interchain-security/pull/1503

**Comment by freak12techno** [comment]
@mpoke whoops, didn't notice that one. Do you think it's worth having what I did then?

**Comment by mpoke** [comment]
>  whoops, didn't notice that one. Do you think it's worth having what I did then?

@freak12techno Only if there is a use case that cannot be covered with the existing query.

**Comment by mpoke** [comment]
@freak12techno https://github.com/cosmos/interchain-security/pull/1503 was merged and it's part of ICS [v3.3.0](https://github.com/cosmos/interchain-security/releases/tag/v3.3.0), which will end up on Gaia v15 (the next release on Gaia). Please let us know if that is sufficient to close https://github.com/cosmos/interchain-security/issues/984 and the corresponding Gaia issue https://github.com/cosmos/gaia/issues/2555.

**Comment by freak12techno** [comment]
@mpoke I think that's sufficient, feel free to close

**Pull request closed without merging**
