### PR TITLE
circuit breaker params 

### PR DESCRIPTION
**Pull request by smarshall-spitzbart**
A PR separated from the full circuit breaker implementation (which is now called "slash packet throttling" #462). Just adding params here

### CODE REVIEW

**Review by jtremback — APPROVED** [review]
LGTM, will probably merge it alongside the other one

**Review by mpoke — APPROVED** [review]
LGTM

**Review by danwt — APPROVED** [review]
LGTM

**Comment by smarshall-spitzbart** [comment]
Merging because this PR shouldn't affect safety at all, I'll then fix the merge conflicts for #382

**Pull request merged**
