### PR TITLE
chore: use go 1.20

### PR DESCRIPTION
**Pull request by faddat**
# Description

This PR updates go to the latest version, v1.20.

There are gzip differences between go 1.18 and 1.19, so this is a breaking change and shouldn't be backported to live chains. (1.20 has this change too) 

## Type of change

If you've checked more than one of the first three boxes, consider splitting this PR into multiple PRs!

- [ ] `Feature`: Changes and/or adds code behavior, irrelevant to bug fixes
- [x] `Fix`: Changes and/or adds code behavior, specifically to fix a bug
- [ ] `Refactor`: Changes existing code style, naming, structure, etc.
- [ ] `Testing`: Adds testing
- [ ] `Docs`: Adds documentation

## Regression tests

If `Refactor`, describe the new or existing tests that verify no behavior was changed or added where refactors were introduced.

## New behavior tests

If `Feature` or `Fix`, describe the new or existing tests that verify the new behavior is correct and expected.

## Versioning Implications

- [ ] This PR will affect [semantic versioning as defined for ICS](../CONTRIBUTING.md#semantic-versioning)

If the above box is checked, which version should be bumped?

- [x] `MAJOR`: Consensus breaking changes to both the provider and consumers(s), including updates/breaking changes to IBC communication between provider and consumer(s)
- [ ] `MINOR`: Consensus breaking changes which affect either only the provider or only the consumer(s)
- [ ] `PATCH`: Non consensus breaking changes

## Targeting

Please select one of the following:

- [x] This PR is only relevant to main
- [ ] This PR is relevant to main, and should also be back-ported to ____ (ex: v1.0.0 and v1.1.0)
- [ ] This PR is only relevant to ____ (ex: v1.0.0, v1.1.0, and v1.2.0)

### CODE REVIEW

**Comment by faddat** [comment]
Please let me know if it's preferable to make a PR that doesn't pass the linter as in the case of #805 -- I can revert the ioutil removal.

**Review by smarshall-spitzbart — APPROVED** [review]
LGTM

**Comment by mpoke** [comment]
@faddat Thanks for the contribution. Is there a reason to not jump directly to go 1.20? cc @smarshall-spitzbart

**Comment by faddat** [comment]
My personal preference is 1.20. I'll update it before getting on my flight.

**Comment by faddat** [comment]
seems after the flight instead.

**Comment by faddat** [comment]
oh hey I need to update the other files, 1 moment

**Comment by smarshall-spitzbart** [comment]
@faddat should we also update the `compat` arg in `protocgen.sh`?

**Review by sainoe — APPROVED** [review]

**Comment by faddat** [comment]
100%

**Pull request merged**
