### PR TITLE
add consumer onboarding documentation

### PR DESCRIPTION
**Pull request by MSalopek**
# Description

This PR adds a consumer chain onboarding checklist with additional info.

## Linked issues

Closes: #377 

## Type of change

If you've checked more than one of the first three boxes, consider splitting this PR into multiple PRs!

- [ ] `Feature`: Changes and/or adds code behavior, irrelevant to bug fixes
- [ ] `Fix`: Changes and/or adds code behavior, specifically to fix a bug
- [ ] `Refactor`: Changes existing code style, naming, structure, etc.
- [ ] `Testing`: Adds testing
- [x] `Docs`: Adds documentation

### CODE REVIEW

**Comment by MSalopek** [comment]
TODO:
Expand the testing section with the following details
- how to use ics e2e and integration tests to confirm ICS protocol functionality
- sovereign chain transition to ICS

**Comment by sainoe** [comment]
Perhaps add a section to compute the genesis hashes like it's done here [here](https://github.com/hyphacoop/ics-testnets/tree/main/game-of-chains-2022/sputnik#chain-data)

**Comment by MSalopek** [comment]
Remaining work is tracked in #750

**Comment by smarshall-spitzbart** [comment]
@MSalopek this md was added to `meta/docs` in https://github.com/cosmos/interchain-security/commit/f09cd8736b13aff13d42fb8a456d7e75c2b2cb14. I'll close this PR

**Pull request closed without merging**
