### PR TITLE
Drop duplicate spawn/stop proposals

### PR DESCRIPTION
**Pull request by mpoke**
Closes https://github.com/cosmos/interchain-security/issues/155

### CODE REVIEW

**Review by sainoe — APPROVED** [review]
LGTM
Nice work @mpoke

**Comment by smarshall-spitzbart** [comment]
Regarding [this comment ](https://github.com/cosmos/interchain-security/issues/160#issuecomment-1209576451), I believe this PR is not implemented as mentioned, right? An error can be returned [here](https://github.com/cosmos/interchain-security/blob/cf4402035f8c5fc4affbc142252a1ded10dd0447/x/ccv/provider/keeper/proposal.go#L122), and could invoke a panic [here](https://github.com/cosmos/interchain-security/blob/cf4402035f8c5fc4affbc142252a1ded10dd0447/x/ccv/provider/keeper/proposal.go#L275)

**Comment by mpoke** [comment]
> Regarding [this comment ](https://github.com/cosmos/interchain-security/issues/160#issuecomment-1209576451), I believe this PR is not implemented as mentioned, right? An error can be returned [here](https://github.com/cosmos/interchain-security/blob/cf4402035f8c5fc4affbc142252a1ded10dd0447/x/ccv/provider/keeper/proposal.go#L122), and could invoke a panic [here](https://github.com/cosmos/interchain-security/blob/cf4402035f8c5fc4affbc142252a1ded10dd0447/x/ccv/provider/keeper/proposal.go#L275)

You are right.

**Review by smarshall-spitzbart — APPROVED** [review]
Looks great!

**Pull request merged**
