### PR TITLE
ADR: equivocation gov proposal

### PR DESCRIPTION
**Pull request by tbruyelle**
# Description

Adds a new ADR related to the addition of the equivocation gov proposal, and the disabling of the consumer initiated slashing.

Since the PR that implements the new gov proposal is merged, I considered the status of this ADR `accepted`.

## Type of change

- [x] `Docs`: Adds documentation

### CODE REVIEW

**Comment by smarshall-spitzbart** [comment]
Thanks for the contribution! Could you change the relevant ADR number instances from 2 -> 3, as I've just opened [this PR](https://github.com/cosmos/interchain-security/pull/682) for a feature that was merged a couple months ago. Probably best to keep things in the order they were merged

**Comment by tbruyelle** [comment]
> Thanks for the contribution! Could you change the relevant ADR number instances from 2 -> 3, as I've just opened [this PR](https://github.com/cosmos/interchain-security/pull/682) for a feature that was merged a couple months ago. Probably best to keep things in the order they were merged

Done!

**Review by smarshall-spitzbart — APPROVED** [review]
LGTM thanks!

**Review by MSalopek — APPROVED** [review]
IIUC we can inspect IBC releated events on the provider to confirm that an equivocation slash packet was accepted by the provider. The packet is dropped, but the event about it being received will remain.

**Review by jtremback — APPROVED** [review]
LGTM

**Pull request merged**
