### PR TITLE
other: remove depguard and bump golangci-lint

### PR DESCRIPTION
**Pull request by faddat**
## Description

This pull request removes the depguard linter, which suddenly started to work in an upgrade of golangci-lint and really isn't very useful in this setting. It also bumps golangci-lint to v1.5.3.

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [x] Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] Added `!` to the type prefix if state-machine breaking change (i.e., requires coordinated upgrade)
* [ ] Confirmed this PR does not introduce changes requiring state migrations, OR migration code has been added to consumer and/or provider modules
* [x] Targeted the correct branch (see [PR Targeting](https://github.com/cosmos/interchain-security/blob/main/CONTRIBUTING.md#pr-targeting))
* [ ] Provided a link to the relevant issue or specification
* [ ] Followed the guidelines for [building SDK modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules)
* [ ] Included the necessary unit and integration [tests](https://github.com/cosmos/interchain-security/blob/main/CONTRIBUTING.md#testing)
* [ ] Added a changelog entry to `CHANGELOG.md`
* [ ] Included comments for [documenting Go code](https://blog.golang.org/godoc)
* [ ] Updated the relevant documentation or specification
* [ ] Reviewed "Files changed" and left comments if necessary 
* [x] Confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed `!` in the type prefix if API or client breaking change
* [ ] confirmed this PR does not introduce changes requiring state migrations, OR confirmed migration code has been added to consumer and/or provider modules
* [ ] confirmed all author checklist items have been addressed
* [ ] reviewed state machine logic
* [ ] reviewed API design and naming
* [ ] reviewed documentation is accurate
* [ ] reviewed tests and test coverage

I apologize because there is no preview tab when using 
`gh` and in fact I dont know which preview tab this 
refers to. 

This PR removes depguard and bumps golangci-lint to 
v1.53.3

Please go the the `Preview` tab and select the appropriate sub-template:

* [Production code](?expand=1&template=production.md) - for types `fix`, `feat`, and `refactor`.
* [Docs](?expand=1&template=docs.md) - for documentation changes.
* [Others](?expand=1&template=others.md) - for changes that do not affect production code.

### CODE REVIEW

**Comment by smarshall-spitzbart** [comment]
To use the proper PR template:
See
Screenshot 2023-06-23 at 11 18 48

or if not using github you can copy/paste manually from https://github.com/cosmos/interchain-security/tree/main/.github/PULL_REQUEST_TEMPLATE

**Comment by smarshall-spitzbart** [comment]
See https://github.com/cosmos/interchain-security/pull/990. We were having issues with the latest golangci-lint so we hardcoded a version that's functional

**Comment by faddat** [comment]
@smarshall-spitzbart -- thanks very much for the preview tab link, I get where we're going with the templates now.  

This PR also hard-codes a version, the latest one (also functional) -- likely the thing that made it non-functional is that `depguard` suddenly started working.

**Comment by jtremback** [comment]
Tests not passing on this one

**Review by mpoke — APPROVED** [review]

**Comment by faddat** [comment]
@jtremback -- I think the tests pass?

CI seems to say so

**Comment by faddat** [comment]
oh, there they are :)

**Comment by faddat** [comment]
This doesn't change any files.  @mpoke do you have any idea why it does not pass `gosec`?

**Review by smarshall-spitzbart — APPROVED** [review]

**Pull request merged**
