### PR TITLE
ci: add codespell nightly workflow

### PR DESCRIPTION
**Pull request by mpoke**
## Description

Closes: NA

Add workflow that opens PRs to fix spelling errors

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [x] Targeted the correct branch (see [PR Targeting](https://github.com/cosmos/interchain-security/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Provided a link to the relevant issue or specification
- [x] Reviewed "Files changed" and left comments if necessary 
- [x] Confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] Confirmed all author checklist items have been addressed
- [ ] Confirmed that this PR does not change production code

### CODE REVIEW

**Comment by insumity** [comment]
The way I understand this, this might create a PR every day with just spell corrections (?)
Is there a way to run this on every PR before it gets merged instead? This way, we only have it to run _once_ against the whole repo and then each PR would always get spell checked before it gets merged.

**Comment by mpoke** [comment]
> The way I understand this, this might create a PR every day with just spell corrections (?) 

Indeed 


> Is there a way to run this on every PR before it gets merged instead? This way, we only have it to run _once_ against the whole repo and then each PR would always get spell checked before it gets merged.

Not sure how to do that. This solution was taken from the SDK repo :)

**Comment by p-offtermatt** [comment]
Let's do this for now and refactor if it becomes annoying?

**Review by p-offtermatt — APPROVED** [review]

**Review by bermuell — APPROVED** [review]
minor: pls add new lines at the end of the files

**Pull request merged**
